-- Tablas que los scrapers ya referencian (P_aguila en SQL Server).
-- En este servidor viven en PostgreSQL, esquema public, y se purgan a los 3 días.

CREATE TABLE IF NOT EXISTS medicamentos_altos_costos_america (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais VARCHAR(80) NOT NULL,
    farmacia VARCHAR(80) NOT NULL,
    fuente_url VARCHAR(500),
    id_producto_farmacia VARCHAR(80) NOT NULL,
    sku VARCHAR(80),
    n_lista INTEGER NOT NULL,
    medicamento_lista VARCHAR(300) NOT NULL,
    programa VARCHAR(40),
    nombre_comercial VARCHAR(500),
    principio_activo VARCHAR(500),
    concentracion VARCHAR(300),
    cantidad_concentracion VARCHAR(80),
    unidad_concentracion VARCHAR(40),
    presentacion VARCHAR(120),
    tipo_presentacion VARCHAR(80),
    cantidad_presentacion VARCHAR(80),
    alcance_presentacion VARCHAR(20),
    laboratorio VARCHAR(200),
    precio NUMERIC(18, 4),
    precio_lista NUMERIC(18, 4),
    precio_oferta NUMERIC(18, 4),
    moneda CHAR(3) NOT NULL,
    disponibilidad VARCHAR(40),
    calidad VARCHAR(20) NOT NULL,
    observacion VARCHAR(400),
    fecha_publicacion TIMESTAMP,
    fecha_dato DATE NOT NULL,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_mac_ame UNIQUE (pais, farmacia, id_producto_farmacia, n_lista)
);

CREATE INDEX IF NOT EXISTS ix_mac_ame_fecha ON medicamentos_altos_costos_america (fecha_dato);
CREATE INDEX IF NOT EXISTS ix_mac_ame_farmacia ON medicamentos_altos_costos_america (pais, farmacia);

CREATE TABLE IF NOT EXISTS medicamentos_precios_historial (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    n_lista INTEGER NOT NULL,
    medicamento_lista VARCHAR(300) NOT NULL,
    programa VARCHAR(40),
    producto_key VARCHAR(500) NOT NULL,
    pais VARCHAR(80) NOT NULL,
    farmacia VARCHAR(80) NOT NULL,
    nombre_comercial VARCHAR(500),
    concentracion VARCHAR(300),
    presentacion VARCHAR(120),
    precio NUMERIC(18, 4),
    moneda CHAR(3),
    precio_usd NUMERIC(18, 6),
    precio_lista NUMERIC(18, 4),
    precio_oferta NUMERIC(18, 4),
    fuente_url VARCHAR(500),
    fecha_dato DATE NOT NULL,
    fecha_vista DATE NOT NULL,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT uq_mac_ph UNIQUE (fecha_dato, n_lista, pais, farmacia, producto_key)
);

CREATE INDEX IF NOT EXISTS ix_mac_ph_fecha ON medicamentos_precios_historial (fecha_dato);

CREATE TABLE IF NOT EXISTS medicamentos_scrape_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fuente_id VARCHAR(40) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    solicitado_por VARCHAR(80),
    argv_json VARCHAR(400),
    log_path VARCHAR(500),
    mensaje VARCHAR(1000),
    exit_code INTEGER,
    worker_id VARCHAR(80),
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_mac_job_estado ON medicamentos_scrape_jobs (estado, id);
CREATE INDEX IF NOT EXISTS ix_mac_job_fuente ON medicamentos_scrape_jobs (fuente_id, estado);

CREATE TABLE IF NOT EXISTS medicamentos_cron_corridas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_corrida DATE NOT NULL,
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP,
    estado VARCHAR(30) NOT NULL,
    argv_json VARCHAR(400),
    mensaje VARCHAR(1000),
    total_pasos INTEGER NOT NULL DEFAULT 0,
    total_ok INTEGER NOT NULL DEFAULT 0,
    total_cache INTEGER NOT NULL DEFAULT 0,
    total_warn INTEGER NOT NULL DEFAULT 0,
    total_error INTEGER NOT NULL DEFAULT 0,
    total_skip INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS ix_mac_cr_fecha ON medicamentos_cron_corridas (fecha_corrida, id DESC);

CREATE TABLE IF NOT EXISTS medicamentos_cron_pasos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corrida_id INTEGER NOT NULL,
    orden INTEGER NOT NULL,
    fuente_id VARCHAR(60) NOT NULL,
    nombre VARCHAR(120),
    script VARCHAR(200),
    pais VARCHAR(80),
    farmacia VARCHAR(120),
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP,
    duracion_ms INTEGER,
    estado VARCHAR(20) NOT NULL,
    exit_code INTEGER,
    filas_merge INTEGER,
    mensaje VARCHAR(1000),
    detalle TEXT
);

CREATE INDEX IF NOT EXISTS ix_mac_cp_corrida ON medicamentos_cron_pasos (corrida_id, orden);
CREATE INDEX IF NOT EXISTS ix_mac_cp_fuente ON medicamentos_cron_pasos (fuente_id, fin DESC);
